# Generated by Django 4.2.1 on 2024-12-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('kk', 'Казахский')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
