# Generated by Django 4.2.17 on 2024-12-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_cleaner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textdata",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("en", "Английский")], max_length=2
            ),
        ),
    ]
