# Generated by Django 4.2.17 on 2024-12-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_cleaner", "0002_alter_textdata_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textdata",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("en", "Английский")],
                default="auto",
                max_length=5,
            ),
        ),
    ]
